version: '3.7'
services:
  node:
    image: 'node:14'
    working_dir: '/home/node/app'
    volumes:
      - '../app:/home/node/app'
    ports: 
      - '3000:3000'
    environment:
      - CI=true #This allows the develop server to work in a docker container.
      - REACT_APP_API_URL=$REACT_APP_API_URL
    command: 'yarn start'